name = App-Rak-Complete

[ReadmeFromPod]
; enabled = false
filename = doc/App-Rak-Complete.rakudoc

[UploadToZef]

[PruneFiles]
; match = ^ 'xt/'

[Badges]
provider = github-actions/linux.yml
provider = github-actions/macos.yml
